nb/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using nb.Infrastructure;
using nb.Models;

namespace nb.Controllers
{
	public class DataController : ApiController
	{
		readonly IBaseRepository<Need> NeedRepository;

		public DataController(IBaseRepository<Need> needRepository)
		{
			NeedRepository = needRepository;
		}

		[HttpGet]
		public Need GetSingleById(int id)
		{
			return NeedRepository.Query().FirstOrDefault(x => x.Id == id);
		}

	}
}

nb/Controllers/HomeController.cs
using System;
using System.Web.Mvc;
using nb.Infrastructure;
using nb.Models;
using System.Linq;

namespace nb.Controllers
{
	public class HomeController : Controller
	{
		readonly IBaseRepository<Need> NeedsRepository;
		readonly IBaseRepository<Location> LocationRepository;

		public HomeController(IBaseRepository<Need> needsRepository, IBaseRepository<Location> locationRepository){
			NeedsRepository = needsRepository;
			LocationRepository = locationRepository;

			if (!locationRepository.Query().Any()){
				LocationRepository.Save(new Location() {
					Name = "Home Base"
				});
				LocationRepository.Save(new Location() {
					Name = "Remote site"
				});
			}
				
		}


		public ActionResult Index()
		{
			ViewBag.TotalRequests = NeedsRepository.Query().Count();

			return View();
		}
	}
}

nb/Controllers/NeedController.cs
using System;
using nb.Infrastructure;
using nb.Models;
using System.Web.Mvc;
using System.Linq;
using System.Collections.Generic;

namespace nb
{
	public class NeedController : Controller
	{
		readonly IBaseRepository<Need> NeedRepository;
		readonly IBaseRepository<Location> LocationRepository;

		public NeedController(IBaseRepository<Need> needRepository, 
		                      IBaseRepository<Location> locationRepository)
		{
			NeedRepository = needRepository;
			LocationRepository = locationRepository;
		}

		public ActionResult Index()
		{
			var nl = NeedRepository.Query().ToList();
			return View(nl);
		}

		public ActionResult Create()
		{
			IEnumerable<SelectListItem> ls = from l in LocationRepository.Query()
					 select new SelectListItem() { Text = l.Name, Value = l.Id.ToString() };
			ViewBag.Locations = ls.ToList();

			var need = new Need() {
				CreateDate = DateTime.Now
			};

			return View(need);
		}

		[HttpPost, ValidateAntiForgeryToken]
		public ActionResult Create(Need need)
		{
			IEnumerable<SelectListItem> ls = from l in LocationRepository.Query()
				select new SelectListItem() { Text = l.Name, Value = l.Id.ToString()};
			ViewBag.Locations = ls.ToList();

			                               
			if (ModelState.IsValid) {
				need.Location = LocationRepository.Query().Single(x => x.Id == need.Location.Id);
				need.CreateDate = DateTime.Now;
				NeedRepository.Save(need);
				return RedirectToAction("Index");
			}

			return View(need);
		}



	}
}

nb/Views/Home/Index.cshtml
	

	<div class="jumbotron">
		<h1>Requests Outstanding @ViewBag.TotalRequests</h1>
		<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
		<p>
			@Html.ActionLink("Add Request", "Create", "Need")
		</p>
	</div>

	<div class="row marketing">
		<div class="col-lg-6">
		<h4>Subheading</h4>
		<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
		</div>

		<div class="col-lg-6">
		<h4>Subheading</h4>
		<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
	</div>
</div>

nb/Views/Need/Create.cshtml
@using System.Collections.Generic
@using System.Web.Mvc
@model nb.Models.Need

<h2>Add a Request</h2>

@using (Html.BeginForm("Create", "Need", FormMethod.Post, new { @class = "form-horizontal"}))
{
	   @Html.AntiForgeryToken() 
 
       <legend>Create New Request</legend>

       <div class="form-group">
           <div>
               @Html.LabelFor(model => model.Name, new {@class = "form-label"})
           </div>
           <div class="editor-field">
               @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder="Name"} })
               @Html.ValidationMessageFor(model => model.Name)
           </div>
		</div>

		<div class="form-group">
           <div>
               @Html.LabelFor(model => model.Location, new {@class = "form-label"})
           </div>
           <div class="editor-field">
		
				@Html.DropDownListFor(model => model.Location.Id, (IEnumerable<SelectListItem>)ViewBag.Locations, new { @class = "form-control"})
           </div>
		</div>

		<div class="form-group text-right">
			<input type="submit" value="Create"  class="btn btn-default"/>
		</div>

}

nb/Views/Need/Details.cshtml
@using nb.Models
@model Need

@Model.Id
@Model.Name
@Model.CreateDate

nb/Views/Need/Edit.cshtml
@model nb.Models.Need

<h2>Edit Request @Model.Id</h2>

@using (Html.BeginForm())
{
   @Html.AntiForgeryToken() 


   <fieldset>
       <legend></legend>

       <div >
           <div class="editor-label">
               @Html.LabelFor(model => model.Name)
           </div>
           <div class="editor-field">
               @Html.EditorFor(model => model.Name)
               @Html.ValidationMessageFor(model => model.Name)
           </div>
		</div>
	</fieldset>
	<p>
       <input type="submit" value="Create" />
   </p>
}

nb/Views/Need/Index.cshtml
@model IList<nb.Models.Need>

<div>
	
   <h2>Outstanding Needs</h2>
	
   <a rel='feedurl' href='/Dinners/WebSliceUpcoming' style='display: none;'></a>
   <ul class="">
       @foreach (var need in Model) {        
           <li>
               @Html.ActionLink(need.Name, "Details", new { id = need.Id })
               on <strong>@need.CreateDate.ToString("HH:mm tt")</strong> 
           </li>
       }
   </ul>
</div>

nb/Views/Shared/_Layout.cshtml
@using System.Web.Optimization


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@ViewBag.Title</title>

	@Styles.Render("~/Content/bootstrap")

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

	 <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation">@Html.ActionLink("Home", "Index", "Home")</li>
            <li role="presentation">@Html.ActionLink("Add Request", "Create", "Need")</li>
            <li role="presentation">@Html.ActionLink("See Requests", "Index", "Need")</li>
          </ul>
        </nav>
        <h3 class="text-muted">Nb</h3>
      </div>

		@RenderBody()

      

      <footer class="footer">
        <p>&copy; 2016 Nb</p>
      </footer>

    </div> <!-- /container -->


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

  </body>
</html>